# Generated by Django 3.1 on 2020-08-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('BULK', 'BULK'), ('EVENT', 'EVENT'), ('OTHER', 'OTHER')], max_length=64)),
                ('job_name', models.CharField(max_length=64)),
                ('job_desc', models.TextField()),
                ('job_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_permanent', models.BooleanField(default=False)),
                ('req_qty', models.PositiveIntegerField()),
                ('pay_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_amt_unit', models.CharField(choices=[('Minute', 'Minute'), ('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year'), ('TASK', 'TASK')], max_length=64)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_accom_avail', models.BooleanField(default=False)),
                ('is_ad', models.BooleanField(default=False)),
                ('job_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
