# Generated by Django 3.1 on 2020-08-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qty_filled',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
