# Generated by Django 3.1 on 2020-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200824_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_img',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=1024, null=True, upload_to='jobs/%Y/%m/', width_field='picture_width'),
        ),
    ]
