# Generated by Django 3.0.5 on 2020-08-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200825_2035'),
        ('jobs', '0004_job_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
            preserve_default=False,
        ),
    ]
