# Generated by Django 3.0.5 on 2020-08-25 16:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200825_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
