# Generated by Django 3.0.5 on 2020-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
