# Generated by Django 3.1 on 2020-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line', models.CharField(max_length=1024)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA')], max_length=64)),
                ('div_1_state', models.CharField(max_length=64)),
                ('div_2_dist', models.CharField(max_length=64)),
                ('div_3_subdist', models.CharField(max_length=64)),
                ('div_4_vill_colony', models.CharField(max_length=64)),
                ('zip', models.PositiveIntegerField()),
                ('lat', models.DecimalField(decimal_places=20, max_digits=23)),
                ('long', models.DecimalField(decimal_places=20, max_digits=23)),
            ],
        ),
    ]
